spring:
    application:
        name: Trilogy
    datasource:
        url: ${db-url}
        username: app_user
        password: secret
    main:
      banner-mode: 'off'
flyway:
  enabled: false
logging:
  pattern:
    console: ''