CREATE OR REPLACE PROCEDURE VALIDATE_BALANCE(
  V_CLIENT_ID IN NUMBER,
  V_IS_VALID OUT NUMBER
) AS
BEGIN
  SELECT CASE C.BALANCE - COALESCE(SUM(T.VALUE), 0) WHEN 0 THEN 1 ELSE 0 END INTO V_IS_VALID
    FROM CLIENTS C LEFT JOIN TRANSACTIONS T ON T.ID_CLIENT=C.ID WHERE C.ID=V_CLIENT_ID GROUP BY C.ID, C.BALANCE;
END;