-- USER SQL
CREATE USER app_user IDENTIFIED BY secret
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO app_user ;
GRANT "DV_MONITOR" TO app_user ;
GRANT "CTXAPP" TO app_user ;
GRANT "DV_AUDIT_CLEANUP" TO app_user ;
GRANT "SPATIAL_CSW_ADMIN" TO app_user ;
GRANT "APEX_GRANTS_FOR_NEW_USERS_ROLE" TO app_user ;
GRANT "WFS_USR_ROLE" TO app_user ;
GRANT "EM_EXPRESS_ALL" TO app_user ;
GRANT "WM_ADMIN_ROLE" TO app_user ;
GRANT "OLAP_USER" TO app_user ;
GRANT "OLAP_XS_ADMIN" TO app_user ;
GRANT "DV_SECANALYST" TO app_user ;
GRANT "CSW_USR_ROLE" TO app_user ;
GRANT "XS_CACHE_ADMIN" TO app_user ;
GRANT "GDS_CATALOG_SELECT" TO app_user ;
GRANT "SCHEDULER_ADMIN" TO app_user ;
GRANT "PROVISIONER" TO app_user ;
GRANT "AUDIT_ADMIN" TO app_user ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO app_user ;
GRANT "DV_REALM_RESOURCE" TO app_user ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO app_user ;
GRANT "DELETE_CATALOG_ROLE" TO app_user ;
GRANT "XDB_WEBSERVICES" TO app_user ;
GRANT "DV_PUBLIC" TO app_user ;
GRANT "LBAC_DBA" TO app_user ;
GRANT "OPTIMIZER_PROCESSING_RATE" TO app_user ;
GRANT "RECOVERY_CATALOG_USER" TO app_user ;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO app_user ;
GRANT "GSMUSER_ROLE" TO app_user ;
GRANT "GATHER_SYSTEM_STATISTICS" TO app_user ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO app_user ;
GRANT "GSM_POOLADMIN_ROLE" TO app_user ;
GRANT "DV_ADMIN" TO app_user ;
GRANT "HS_ADMIN_ROLE" TO app_user ;
GRANT "XS_SESSION_ADMIN" TO app_user ;
GRANT "DV_GOLDENGATE_ADMIN" TO app_user ;
GRANT "IMP_FULL_DATABASE" TO app_user ;
GRANT "DV_XSTREAM_ADMIN" TO app_user ;
GRANT "DV_PATCH_ADMIN" TO app_user ;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO app_user ;
GRANT "EJBCLIENT" TO app_user ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO app_user ;
GRANT "JMXSERVER" TO app_user ;
GRANT "OLAP_DBA" TO app_user ;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO app_user ;
GRANT "JAVAIDPRIV" TO app_user ;
GRANT "SELECT_CATALOG_ROLE" TO app_user ;
GRANT "JAVADEBUGPRIV" TO app_user ;
GRANT "CONNECT" TO app_user ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO app_user ;
GRANT "OEM_MONITOR" TO app_user ;
GRANT "APEX_ADMINISTRATOR_ROLE" TO app_user ;
GRANT "GSMADMIN_ROLE" TO app_user ;
GRANT "AQ_USER_ROLE" TO app_user ;
GRANT "JAVAUSERPRIV" TO app_user ;
GRANT "XDB_SET_INVOKER" TO app_user ;
GRANT "RECOVERY_CATALOG_OWNER" TO app_user ;
GRANT "JAVA_ADMIN" TO app_user ;
GRANT "DBFS_ROLE" TO app_user ;
GRANT "PDB_DBA" TO app_user ;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO app_user ;
GRANT "CDB_DBA" TO app_user ;
GRANT "JAVASYSPRIV" TO app_user ;
GRANT "HS_ADMIN_SELECT_ROLE" TO app_user ;
GRANT "AUDIT_VIEWER" TO app_user ;
GRANT "RESOURCE" TO app_user ;
GRANT "DV_OWNER" TO app_user ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO app_user ;
GRANT "EXECUTE_CATALOG_ROLE" TO app_user ;
GRANT "DV_ACCTMGR" TO app_user ;
GRANT "DV_REALM_OWNER" TO app_user ;
GRANT "EXP_FULL_DATABASE" TO app_user ;
GRANT "DV_STREAMS_ADMIN" TO app_user ;
GRANT "JAVA_DEPLOY" TO app_user ;
GRANT "SPATIAL_WFS_ADMIN" TO app_user ;
GRANT "XS_NAMESPACE_ADMIN" TO app_user ;
GRANT "XS_RESOURCE" TO app_user ;
GRANT "ORDADMIN" TO app_user ;
GRANT "AUTHENTICATEDUSER" TO app_user ;
GRANT "CAPTURE_ADMIN" TO app_user ;
GRANT "OEM_ADVISOR" TO app_user ;
GRANT "XDBADMIN" TO app_user ;
GRANT "EM_EXPRESS_BASIC" TO app_user ;

-- SYSTEM PRIVILEGES
GRANT MANAGE TABLESPACE TO app_user ;