---
resources:
- name: trilogy
  type: git
  source:
    uri: https://github.com/PivotalSharedIreland/trilogy.git
    branch: master

jobs:
- name: trilogy-tests
  plan:
  - get: trilogy
    trigger: true
  - task: tests
    file: trilogy/ci/test.yml